# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accredited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReferredAngel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Angel')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Angel'), ('E', 'Entrepreneur'), ('SE', 'Successful founder')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('review', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SerialEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Person')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Reviews')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angel_profile', models.CharField(max_length=200)),
                ('crunchbase_profile', models.CharField(max_length=200)),
                ('twitter_profile', models.CharField(max_length=200)),
                ('linkedin_profile', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='serialentrepreneur',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.SocialProfile'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='given_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Score'),
        ),
        migrations.AddField(
            model_name='referredangel',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.SerialEntrepreneur'),
        ),
        migrations.AddField(
            model_name='referredangel',
            name='why',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Reviews'),
        ),
        migrations.AddField(
            model_name='angel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Person'),
        ),
        migrations.AddField(
            model_name='angel',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Reviews'),
        ),
        migrations.AddField(
            model_name='angel',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.SocialProfile'),
        ),
    ]
